name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ["delphes/ubuntu:24.04", "delphes/fedora:42"]

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build AgrippaSim using cmake
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake ..
          make -j 8
